name: Auto NIC packager
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Theos
        run: |
          export THEOS=/opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Setup SDK
        run: |
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Package
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RespawPurple-Dylib
          path: packages/*.deb
